### ISSUE TITLE
$basketItem cannot be used as an array

### ISSUE THREAD

**Issue by Mirlen** [darkfriend/bitrix_dev2fun.stripepayment#7]
https://github.com/darkfriend/bitrix_dev2fun.stripepayment/blob/f63c2d7a321aceaca15804398b00008c415ca4af/utf8/dev2fun.stripepayment/install/sale_payment/stripe/payment.php#L107

**$basketItem** cannot be used as an array
please, replace with **$product**

**Comment by darkfriend** [comment]
Спасибо, поправлю

**Comment by darkfriend** [comment]
поправлено в 1.3.10
