### ISSUE TITLE
В настройках ПС не появляются свои шаблоны

### ISSUE THREAD

**Issue by megamosk** [darkfriend/bitrix_dev2fun.stripepayment#8]
Привет,

Спасибо за отличный компонент, очень сэкономит время. 

Пробую использовать его с собственным шаблоном, но в настройках ПС не вижу его.

Размещать пробовал тут
```
/local/php_interface/sale_payment/stripe/templates/
/bitrix/php_interface/sale_payment/stripe/templates/
```
но без результата, видны только шаблоны по умолчанию

![Screenshot 2022-04-02 at 19 24 17](https://user-images.githubusercontent.com/2061255/161394208-59b6af4a-003a-4f40-9467-69b9d6b146a4.png)

Свой шаблон появляется только если разместить его в /bitrix/modules/dev2fun.stripepayment/sale_payment/stripe/templates/%template_name%/

ЗЫ В документации указан путь /bitrix/templates/<шаблон_сайта>/payment/stripe/template/ и метод  \Bitrix\Sale\PaySystem\BaseServiceHandler::searchTemplate() для поиска шаблонов. Но по этому пути тоже не находится

**Comment by megamosk** [comment]
Сообщение выше касается версии из marketplace. Поставил с github 1.3.12 — шаблоны подключаются из bitrix/php_interface/include/sale_payment/stripe/templates/

**Comment by darkfriend** [comment]
Здравствуйте!
Спасибо за обращение.
\
Попробуйте еще раз, проверял на версии `1.4.0` и `1.5.0` работает.\
Если у вас проблема сохранится, то попробуйте проверить доступность папки и файла `templates.php` внутри папки.\
Если же проблема всё равно будет, то дайте знать на почту support@dev2fun.com, желательно с доступами, посмотрю и поправлю.\
\
Приятного использования!
